-- Ascenda optional user seed
-- This file intentionally does not create default users or passwords.
--
-- For migration, create real users through Supabase Auth or the Ascenda
-- registration flow, then promote the first mentor/admin explicitly:
--
-- update public.profiles
-- set role = 'mentor'
-- where email = '<mentor-email>';
--
-- If a scripted seed is needed for a non-production environment, keep the
-- emails and passwords in a private, ignored SQL file instead of committing
-- them to this repository.
